### ISSUE TITLE
Unable to use the C# version of the RPG-Databases script

### ISSUE THREAD

**Issue by Sol-Hero93** [sdtv9507/rpg_database#1]
**Describe the bug**
The following message appears when trying to enable the addon script: "Unable to load addon script from path: 'res://addons/rpg_database/database.cs'. This might be due to a code error in that script.
Disabling the addon at 'res://addons/rpg_database/plugin.cfg' to prevent further errors."

**To Reproduce**
1. Follow the exact steps indicated by the instructions on how to install the addon.
2. The addon appears in project settings.
3. Press enable and the error message appears. 

**Expected behavior**
Being able to use the c# version of the script.

**Screenshots**
N/A

 - OS: Windows 10
 - Godot Version: v3.3.2.stable.mono.official
 
**Additional context**
This bug only appears if I want to use the c# version of the addon.

**Comment by sdtv9507** [comment]
I made a new project and it didin't work. Build the project before enabling the addon. If the build button doesn't show, create a new c# script.

**Comment by sdtv9507** [comment]
I just updated the readme with instructions so I'll close this. If you still hace issues, feel free yo reopen it.
